const $=id=>document.getElementById(id), pad=n=>String(n).padStart(2,'0');
const iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const parse=s=>{const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const today=new Date(), config=window.KYYDIT_CONFIG||{}, isLive=Boolean(config.supabaseUrl&&config.supabaseAnonKey);
let supabase=null,user=null,profile=null,rides=[],profiles=[],selected=iso(today),view=new Date(today.getFullYear(),today.getMonth(),1);
const dateAt=n=>{const d=new Date(today);d.setDate(d.getDate()+n);return iso(d)};
const demo=[
 {id:'d1',ride_date:dateAt(0),ride_time:'07:15',customer:'Maija Korhonen',phone:'040 000 1001',pickup:'Koivukuja 8',destination:'Keskussairaala',status:'confirmed',notes:'Paluu tilataan erikseen'},
 {id:'d2',ride_date:dateAt(0),ride_time:'09:00',customer:'Pekka Laine',phone:'040 000 1002',pickup:'Rautatieasema',destination:'Kauppatori',status:'confirmed',notes:'2 matkalaukkua'},
 {id:'d3',ride_date:dateAt(0),ride_time:'11:30',customer:'Aino Niemi',phone:'040 000 1003',pickup:'Palvelukoti Auringonkukka',destination:'Terveyskeskus',status:'pending',notes:'Rollaattori mukana'},
 {id:'d4',ride_date:dateAt(1),ride_time:'06:40',customer:'Laura Salmi',phone:'040 000 1004',pickup:'Metsätie 4',destination:'Lentoasema',status:'pending',notes:'Soita 5 min ennen'}
];
const fiMonth=new Intl.DateTimeFormat('fi-FI',{month:'long',year:'numeric'}), fiDate=new Intl.DateTimeFormat('fi-FI',{weekday:'long',day:'numeric',month:'long'});
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1800)}
function notice(text,error=false){$('notice').textContent=text;$('notice').classList.toggle('error',error);$('notice').classList.toggle('hidden',!text)}
function showApp(){ $('authView').classList.add('hidden');$('appView').classList.remove('hidden');$('logoutBtn').classList.toggle('hidden',!isLive);$('modeBadge').textContent=isLive?'YHTEISKÄYTTÖ':'ESITTELY';$('modeBadge').className='badge '+(isLive?'live':'demo'); }
function render(){renderCalendar();renderList();renderAssignees();}
function renderCalendar(){
 $('monthTitle').textContent=fiMonth.format(view);const start=new Date(view),offset=(start.getDay()+6)%7;start.setDate(start.getDate()-offset);$('calendar').innerHTML='';
 for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=iso(d),items=rides.filter(r=>r.ride_date===key).sort((a,b)=>a.ride_time.localeCompare(b.ride_time));const b=document.createElement('button');b.type='button';b.className='day'+(d.getMonth()!==view.getMonth()?' outside':'')+(key===selected?' selected':'')+(key===iso(today)?' today':'');b.innerHTML=`<span class="num">${d.getDate()}</span>`+items.slice(0,2).map(r=>`<span class="chip ${r.status}">${esc(r.ride_time.slice(0,5))} ${esc(r.customer)}</span>`).join('')+(items.length>2?`<div class="more">+ ${items.length-2} muuta</div>`:'');b.onclick=()=>{selected=key;view=new Date(d.getFullYear(),d.getMonth(),1);$('date').value=key;render()};$('calendar').appendChild(b)}
}
function driverName(id){return profiles.find(p=>p.id===id)?.full_name||'Ei osoitettu'}
function canManage(){return !isLive||['admin','dispatcher'].includes(profile?.role)}
function renderList(){const items=rides.filter(r=>r.ride_date===selected).sort((a,b)=>a.ride_time.localeCompare(b.ride_time));$('selectedTitle').textContent=fiDate.format(parse(selected));$('count').textContent=items.length;$('rides').innerHTML=items.length?'':'<div class="empty">Ei kyytejä tälle päivälle.</div>';
 items.forEach(r=>{const el=document.createElement('article');el.className='ride';el.innerHTML=`<div class="ride-top"><div><span class="ride-time">${esc(r.ride_time.slice(0,5))}</span> · <span class="ride-name">${esc(r.customer)}</span></div><span>${{confirmed:'✓',pending:'◷',completed:'●',cancelled:'×'}[r.status]}</span></div><div class="route">${esc(r.pickup)} → ${esc(r.destination)}${r.phone?'<br>'+esc(r.phone):''}${r.notes?'<br>'+esc(r.notes):''}</div><div class="driver">Kuljettaja: ${esc(driverName(r.assigned_to))}</div>${canManage()?'<div class="ride-actions"><button class="small edit">Muokkaa</button><button class="small delete">Poista</button></div>':''}`;if(canManage()){el.querySelector('.edit').onclick=()=>editRide(r.id);el.querySelector('.delete').onclick=()=>deleteRide(r.id)}$('rides').appendChild(el)});
 $('formPanel').classList.toggle('hidden',!canManage());
}
function renderAssignees(){$('assigned').innerHTML='<option value="">Ei osoitettu</option>'+profiles.map(p=>`<option value="${esc(p.id)}">${esc(p.full_name||p.email||'Käyttäjä')}</option>`).join('')}
function resetForm(){$('rideForm').reset();$('rideId').value='';$('date').value=selected;$('time').value='09:00';$('formTitle').textContent='Uusi taksitilaus';$('cancelEdit').classList.add('hidden')}
function editRide(id){const r=rides.find(x=>x.id===id);if(!r)return;$('rideId').value=r.id;const map={date:r.ride_date,time:r.ride_time.slice(0,5),customer:r.customer,phone:r.phone,pickup:r.pickup,destination:r.destination,status:r.status,assigned:r.assigned_to||'',notes:r.notes};Object.entries(map).forEach(([k,v])=>$(k).value=v??'');$('formTitle').textContent='Muokkaa tilausta';$('cancelEdit').classList.remove('hidden');scrollTo({top:0,behavior:'smooth'})}
async function deleteRide(id){if(!confirm('Poistetaanko tämä tilaus?'))return;if(isLive){const {error}=await supabase.from('rides').delete().eq('id',id);if(error)return notice(error.message,true)}else rides=rides.filter(r=>r.id!==id);await loadRides();toast('Tilaus poistettu')}
async function loadRides(){if(isLive){const {data,error}=await supabase.from('rides').select('*').order('ride_date').order('ride_time');if(error)return notice('Kyytien lataus epäonnistui: '+error.message,true);rides=data||[]}render()}
async function loadProfiles(){if(!isLive)return;const {data}=await supabase.from('profiles').select('id,full_name,email,role').order('full_name');profiles=data||[];profile=profiles.find(p=>p.id===user.id)||{role:'driver'};render()}
async function initLive(){
 const lib=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm');supabase=lib.createClient(config.supabaseUrl,config.supabaseAnonKey);const {data:{session}}=await supabase.auth.getSession();if(!session){$('authView').classList.remove('hidden');return}user=session.user;showApp();await Promise.all([loadProfiles(),loadRides()]);supabase.channel('rides-live').on('postgres_changes',{event:'*',schema:'public',table:'rides'},loadRides).subscribe();
}
$('authForm').onsubmit=async e=>{e.preventDefault();$('authMessage').textContent='';const {data,error}=await supabase.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(error)return $('authMessage').textContent='Kirjautuminen epäonnistui: '+error.message;user=data.user;showApp();await Promise.all([loadProfiles(),loadRides()])};
$('logoutBtn').onclick=async()=>{await supabase.auth.signOut();location.reload()};
$('rideForm').onsubmit=async e=>{e.preventDefault();const id=$('rideId').value,payload={ride_date:$('date').value,ride_time:$('time').value,customer:$('customer').value.trim(),phone:$('phone').value.trim(),pickup:$('pickup').value.trim(),destination:$('destination').value.trim(),status:$('status').value,assigned_to:$('assigned').value||null,notes:$('notes').value.trim()};if(isLive){const q=id?supabase.from('rides').update(payload).eq('id',id):supabase.from('rides').insert(payload);const {error}=await q;if(error)return notice('Tallennus epäonnistui: '+error.message,true)}else{id?rides=rides.map(r=>r.id===id?{...r,...payload}:r):rides.push({id:crypto.randomUUID(),...payload})}selected=payload.ride_date;view=new Date(parse(selected).getFullYear(),parse(selected).getMonth(),1);resetForm();await loadRides();toast(id?'Muutokset tallennettu':'Tilaus tallennettu')};
$('cancelEdit').onclick=resetForm;$('prev').onclick=()=>{view=new Date(view.getFullYear(),view.getMonth()-1,1);renderCalendar()};$('next').onclick=()=>{view=new Date(view.getFullYear(),view.getMonth()+1,1);renderCalendar()};$('todayBtn').onclick=()=>{selected=iso(today);view=new Date(today.getFullYear(),today.getMonth(),1);resetForm();render()};
$('exportBtn').onclick=()=>{const rows=[['Päivä','Aika','Asiakas','Puhelin','Nouto','Määränpää','Tila','Kuljettaja','Lisätiedot'],...rides.map(r=>[r.ride_date,r.ride_time.slice(0,5),r.customer,r.phone,r.pickup,r.destination,r.status,driverName(r.assigned_to),r.notes])];const csv=rows.map(row=>row.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download='kyydit.csv';a.click();URL.revokeObjectURL(a.href)};
resetForm();
if(isLive){initLive().catch(e=>{$('authView').classList.remove('hidden');$('authMessage').textContent='Yhteysvirhe: '+e.message})}else{rides=[...demo];showApp();notice('Esittelytila: lisää Supabase-tiedot config.js-tiedostoon, jolloin käyttäjät ja yhteinen tietokanta aktivoituvat.');render()}
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./service-worker.js');
